// src/redirects.ts
import type { RedirectConfig } from 'astro';

export const redirects: Record<string, RedirectConfig> = {
  '/pages/federalist-migration/': 'https://docs.cloud.gov/pages/security-compliance/pages-atu-guide',
  '/pages/features/': '/pages',
  '/pages/success-stories/': '/pages',
  '/pages/pricing/': '/pricing',
  '/pages/contact/': '/contact',

  '/pricing/free-limited-sandbox/': '/sign-up',
  '/pricing/quotas/': '/pricing',
  '/docs/pricing/free-limited-sandbox/': '/sign-up',
  '/docs/pricing/quotas/': '/pricing',

  '/news/': 'https://docs.cloud.gov/blog',
  '/updates.xml': 'https://docs.cloud.gov/blog',

  '/docs/customer-stories/epa-airnow-gov/': '/',
  '/docs/customer-stories/fec/': '/',

  '/docs/overview/': 'https://docs.cloud.gov/',
  '/docs/overview/cloudgov-benefits/': '/',
  '/docs/overview/cloudgov-team/': '/',
  '/docs/overview/customer-service-objectives/': '/',
  '/docs/overview/enterprise-approach-to-cloud/': '/',
  '/docs/overview/fedramp-tracker/': '/',
  '/docs/overview/portfolio-analysis/': '/',
  '/docs/overview/using-cloudgov-paas/': '/',
  '/docs/overview/what-is-cloudgov/': '/',
  '/docs/overview/who-can-use-cloudgov/': '/',
  // ^^ docs that aren't docs

  // platform docs
  '/docs/compliance/ato-process/': 'https://docs.cloud.gov/platform/compliance/ato-process',
  '/docs/compliance/auditing-activity/': 'https://docs.cloud.gov/platform/compliance/auditing-activity',
  '/docs/compliance/cisa-directives/': 'https://docs.cloud.gov/platform/compliance/cisa-directive-compliance',
  '/docs/compliance/compliance-community/': 'https://docs.cloud.gov/platform/compliance/compliance-community',
  '/docs/compliance/customer-separation/': 'https://docs.cloud.gov/platform/compliance/customer-separation',
  '/docs/compliance/diagrams/': 'https://docs.cloud.gov/platform/compliance/',
  '/docs/compliance/domain-standards/': 'https://docs.cloud.gov/platform/compliance/domain-security-standards',
  '/docs/compliance/for-assessors/': 'https://docs.cloud.gov/platform/compliance/assessor-overview',
  '/docs/compliance/incident-plans/': 'https://docs.cloud.gov/platform/compliance/incident-response-planning',
  '/docs/compliance/logging-requirements/': 'https://docs.cloud.gov/platform/compliance/meeting-tic-requirements',
  '/docs/compliance/meeting-tic-requirements/': 'https://docs.cloud.gov/platform/compliance/meeting-tic-requirements',
  '/docs/compliance/pentest/': 'https://docs.cloud.gov/platform/compliance/penetration-testing',

  '/docs/deployment/app-maintenance/': 'https://docs.cloud.gov/platform/deployment/app-maintenance',
  '/docs/deployment/assets/': 'https://docs.cloud.gov/platform/deployment/assets',
  '/docs/deployment/custom-buildpacks/': 'https://docs.cloud.gov/platform/deployment/custom-buildpacks',
  '/docs/deployment/deployment/': 'https://docs.cloud.gov/platform/deployment/',
  '/docs/deployment/docker/': 'https://docs.cloud.gov/platform/deployment/docker',
  '/docs/deployment/frameworks/': 'https://docs.cloud.gov/platform/deployment/frameworks',
  '/docs/deployment/logs/': 'https://docs.cloud.gov/platform/deployment/logs',
  '/docs/deployment/managed-services/': 'https://docs.cloud.gov/platform/deployment/managed-services',
  '/docs/deployment/production-ready/': 'https://docs.cloud.gov/platform/deployment/production-ready',
  '/docs/deployment/static/': 'https://docs.cloud.gov/platform/deployment/static',
  '/docs/deployment/troubleshooting/': 'https://docs.cloud.gov/platform/deployment/troubleshooting',

  '/docs/getting-started/accounts/': 'https://docs.cloud.gov/platform/getting-started/account-management',
  '/docs/getting-started/code-samples/': 'https://docs.cloud.gov/platform/getting-started/code-samples',
  '/docs/getting-started/concepts/': 'https://docs.cloud.gov/platform/getting-started/platform-concepts',
  '/docs/getting-started/reference/': 'https://docs.cloud.gov/platform/getting-started/reference',
  '/docs/getting-started/setup/': 'https://docs.cloud.gov/platform/getting-started/initial-setup',
  '/docs/getting-started/your-first-deploy/': 'https://docs.cloud.gov/platform/getting-started/quickstart-setup',

  '/docs/management/Renaming-Spaces/': 'https://docs.cloud.gov/platform/management/renaming-spaces',
  '/docs/management/cloning/': 'https://docs.cloud.gov/platform/management/cloning',
  '/docs/management/container-to-container/': 'https://docs.cloud.gov/platform/management/container-to-container',
  '/docs/management/continuous-deployment/': 'https://docs.cloud.gov/platform/management/continuous-deployment',
  '/docs/management/custom-domains/': 'https://docs.cloud.gov/platform/management/custom-domains',
  '/docs/management/database-backup-restore/': 'https://docs.cloud.gov/platform/management/database-backup-restore',
  '/docs/management/headers/': 'https://docs.cloud.gov/platform/management/headers',
  '/docs/management/leveraging-authentication/': 'https://docs.cloud.gov/platform/management/leveraging-authentication',
  '/docs/management/limits/': 'https://docs.cloud.gov/platform/management/limits',
  '/docs/management/moving-apps/': 'https://docs.cloud.gov/platform/management/moving-apps',
  '/docs/management/multiple-instances/': 'https://docs.cloud.gov/platform/management/multiple-instances',
  '/docs/management/one-off-tasks/': 'https://docs.cloud.gov/platform/management/one-off-tasks',
  '/docs/management/plugins/': 'https://docs.cloud.gov/platform/management/plugins',
  '/docs/management/production-ready/': 'https://docs.cloud.gov/platform/management/production-ready',
  '/docs/management/space-egress/': 'https://docs.cloud.gov/platform/management/space-egress',
  '/docs/management/static-egress/': 'https://docs.cloud.gov/platform/management/static-egress',
  '/docs/management/static/': 'https://docs.cloud.gov/platform/management/static',
  '/docs/management/troubleshooting/': 'https://docs.cloud.gov/platform/management/troubleshooting',
  '/docs/management/using-ssh/': 'https://docs.cloud.gov/platform/management/using-ssh',

  '/docs/orgs-spaces/dashboard/': 'https://docs.cloud.gov/platform/orgs-spaces/dashboard',
  '/docs/orgs-spaces/limits/': 'https://docs.cloud.gov/platform/orgs-spaces/limits',
  '/docs/orgs-spaces/new-org/': 'https://docs.cloud.gov/platform/orgs-spaces/new-org',
  '/docs/orgs-spaces/roles/': 'https://docs.cloud.gov/platform/orgs-spaces/roles',
  '/docs/orgs-spaces/sso/': 'https://docs.cloud.gov/platform/orgs-spaces/sso',

  '/docs/services/app-autoscaler/': 'https://docs.cloud.gov/platform/services/app-autoscaler',
  '/docs/services/aws-elasticache/': 'https://docs.cloud.gov/platform/services/aws-elasticache',
  '/docs/services/aws-elasticsearch/': 'https://docs.cloud.gov/platform/services/aws-elasticsearch',
  '/docs/services/aws-ses/': 'https://docs.cloud.gov/platform/services/aws-elasticache',
  '/docs/services/cdn-route/': 'https://docs.cloud.gov/platform/services/cdn-route',
  '/docs/services/cloud-gov-identity-provider/': 'https://docs.cloud.gov/platform/services/cloud-gov-identity-provider',
  '/docs/services/cloud-gov-service-account/': 'https://docs.cloud.gov/platform/services/cloud-gov-service-account',
  '/docs/services/custom-domains/': 'https://docs.cloud.gov/platform/services/custom-domains',
  '/docs/services/external-domain-service/': 'https://docs.cloud.gov/platform/services/external-domain-service',
  '/docs/services/intro/': 'https://docs.cloud.gov/platform/services/intro',
  '/docs/services/relational-database/': 'https://docs.cloud.gov/platform/services/relational-database',
  '/docs/services/s3/': 'https://docs.cloud.gov/platform/services/s3',

  '/docs/technology/conforming-federal-security-regulations/': 'https://docs.cloud.gov/platform/technology/platform-security-protections',
  '/docs/technology/iaas/': 'https://docs.cloud.gov/platform/technology/infrastructure-overview',
  '/docs/technology/platform-protections/': 'https://docs.cloud.gov/platform/technology/platform-security-protections',
  '/docs/technology/responsibilities/': 'https://docs.cloud.gov/platform/technology/shared-responsibilities',

  // pages docs
  '/pages/documentation/': 'https://docs.cloud.gov/pages/using-pages/getting-started',
  '/pages/documentation/21st-century-idea/': 'https://docs.cloud.gov/pages/using-pages/21st-century-idea',
  '/pages/documentation/access-permissions/': 'https://docs.cloud.gov/pages/using-pages/permissions',
  '/pages/documentation/adding-users/': 'https://docs.cloud.gov/pages/using-pages/add-user',
  '/pages/documentation/automated-site-reports/': 'https://docs.cloud.gov/pages/security-compliance/automated-site-reports',
  '/pages/documentation/before-you-launch/': 'https://docs.cloud.gov/pages/using-pages/before-you-launch',
  '/pages/documentation/build-errors/': 'https://docs.cloud.gov/pages/developers/build-errors',
  '/pages/documentation/bundler-on-pages/': 'https://docs.cloud.gov/pages/developers/bundler-on-pages',
  '/pages/documentation/cache-dependencies/': 'https://docs.cloud.gov/pages/developers/cache-dependencies',
  '/pages/documentation/cloud-gov/': 'https://docs.cloud.gov/pages/developers/cloud-gov',
  '/pages/documentation/content-guide/': 'https://docs.cloud.gov/pages/using-pages/migration-guide',
  '/pages/documentation/custom-domains/': 'https://docs.cloud.gov/pages/using-pages/custom-domains',
  '/pages/documentation/custom-headers/': 'https://docs.cloud.gov/pages/using-pages/custom-headers',
  '/pages/documentation/custom-urls/': 'https://docs.cloud.gov/platform/deployment/custom-buildpacks',
  '/pages/documentation/customer-responsibilities/': 'https://docs.cloud.gov/pages/security-compliance/customer-responsibilities',
  '/pages/documentation/customization/': 'https://docs.cloud.gov/pages/using-pages/customization',
  '/pages/documentation/env-vars-on-pages-builds/': 'https://docs.cloud.gov/pages/developers/env-vars-on-pages-builds',
  '/pages/documentation/external-tools-and-resources/': 'https://docs.cloud.gov/pages/developers/external-tools-and-resources',
  '/pages/documentation/federalist-json/': 'https://docs.cloud.gov/pages/using-pages/federalist-json',
  '/pages/documentation/forms/': 'https://docs.cloud.gov/pages/using-pages/forms',
  '/pages/documentation/getting-started-with-decap-cms/': 'https://docs.cloud.gov/pages/using-pages/getting-started-with-netlify-cms',
  '/pages/documentation/how-builds-work/': 'https://docs.cloud.gov/pages/developers/how-builds-work',
  '/pages/documentation/how-pages-works/': 'https://docs.cloud.gov/pages/developers/how-builds-work',
  '/pages/documentation/included-with-pages/': 'https://docs.cloud.gov/pages/using-pages/included-with-pages',
  '/pages/documentation/large-file-handling/': 'https://docs.cloud.gov/pages/developers/large-file-handling',
  '/pages/documentation/migration-guide/': 'https://docs.cloud.gov/pages/using-pages/migration-guide',
  '/pages/documentation/monorepos-on-pages/': 'https://docs.cloud.gov/pages/developers/monorepos-on-pages',
  '/pages/documentation/node-on-pages/': 'https://docs.cloud.gov/pages/developers/node-on-pages',
  '/pages/documentation/previews/': 'https://docs.cloud.gov/pages/using-pages/previews',
  '/pages/documentation/renaming-site-repository/': 'https://docs.cloud.gov/pages/developers/renaming-site-repository',
  '/pages/documentation/resources/': 'https://docs.cloud.gov/pages/using-pages/resources',
  '/pages/documentation/rvm-on-pages/': 'https://docs.cloud.gov/pages/developers/rvm-on-pages',
  '/pages/documentation/sandbox/': 'https://docs.cloud.gov/pages/using-pages/sandbox',
  '/pages/documentation/search/': 'https://docs.cloud.gov/pages/using-pages/search',
  '/pages/documentation/security-and-compliance/': 'https://docs.cloud.gov/pages/security-compliance/pages-atu-guide',
  '/pages/documentation/supported-site-engines/': 'https://docs.cloud.gov/pages/developers/supported-site-engines',
  '/pages/documentation/templates/': 'https://docs.cloud.gov/pages/developers/node-on-pages',
  '/pages/documentation/why-use-pages/': 'https://docs.cloud.gov/pages/using-pages/why-use-pages',

  // release notes & kb articles
  '/2016/11/18/release-notes/': 'https://docs.cloud.gov/release-notes/2016/11/18/release-notes',
  '/2016/11/30/release-notes/': 'https://docs.cloud.gov/release-notes/2016/11/30/release-notes',
  '/2016/12/14/release-notes/': 'https://docs.cloud.gov/release-notes/2016/12/14/release-notes',
  '/2016/12/28/release-notes/': 'https://docs.cloud.gov/release-notes/2016/12/28/release-notes',
  '/2017/02/01/release-notes/': 'https://docs.cloud.gov/release-notes/2017/02/01/release-notes',
  '/2017/02/10/release-notes/': 'https://docs.cloud.gov/release-notes/2017/02/10/release-notes',
  '/2017/02/28/release-notes/': 'https://docs.cloud.gov/release-notes/2017/02/28/release-notes',
  '/2017/03/14/release-notes/': 'https://docs.cloud.gov/release-notes/2017/03/14/release-notes',
  '/2017/03/27/release-notes/': 'https://docs.cloud.gov/release-notes/2017/03/27/release-notes',
  '/2017/05/05/release-notes/': 'https://docs.cloud.gov/release-notes/2017/05/05/release-notes',
  '/2017/05/22/release-notes/': 'https://docs.cloud.gov/release-notes/2017/05/22/release-notes',
  '/2017/06/01/release-notes/': 'https://docs.cloud.gov/release-notes/2017/06/01/release-notes',
  '/2017/07/10/release-notes/': 'https://docs.cloud.gov/release-notes/2017/02/10/release-notes',
  '/2017/07/18/release-notes/': 'https://docs.cloud.gov/release-notes/2017/07/18/release-notes',
  '/2017/08/02/release-notes/': 'https://docs.cloud.gov/release-notes/2017/08/02/release-notes',
  '/2017/08/16/release-notes/': 'https://docs.cloud.gov/release-notes/2017/08/16/release-notes',
  '/2018/10/30/release-notes/': 'https://docs.cloud.gov/release-notes/2018/10/30/release-notes',
  '/2021/10/15/release-notes/': 'https://docs.cloud.gov/release-notes/2021/10/15/release-notes',
  '/2021/10/29/release-notes/': 'https://docs.cloud.gov/release-notes/2021/10/29/release-notes',
  '/2021/11/18/release-notes/': 'https://docs.cloud.gov/release-notes/2021/11/18/release-notes',
  '/2021/12/22/release-notes/': 'https://docs.cloud.gov/release-notes/2021/12/22/release-notes',
  '/2022/01/21/release-notes/': 'https://docs.cloud.gov/release-notes/2022/01/21/release-notes',
  '/2022/02/04/release-notes/': 'https://docs.cloud.gov/release-notes/2022/02/04/release-notes',
  '/2022/02/17/release-notes/': 'https://docs.cloud.gov/release-notes/2017/02/28/release-notes',
  '/2022/03/04/release-notes/': 'https://docs.cloud.gov/release-notes/2022/03/04/release-notes',
  '/2022/04/14/release-notes/': 'https://docs.cloud.gov/release-notes/2022/04/14/release-notes',
  '/2022/05/12/release-notes/': 'https://docs.cloud.gov/release-notes/2022/05/12/release-notes',
  '/2022/05/26/release-notes/': 'https://docs.cloud.gov/release-notes/2022/05/26/release-notes',
  '/2022/07/08/release-notes/': 'https://docs.cloud.gov/release-notes/2022/07/08/release-notes',
  '/2022/09/29/release-notes/': 'https://docs.cloud.gov/release-notes/2022/09/29/release-notes',
  '/2022/11/23/release-notes/': 'https://docs.cloud.gov/release-notes/2022/11/23/release-notes',
  '/2023/01/05/release-notes/': 'https://docs.cloud.gov/release-notes/2023/01/05/release-notes',
  '/2023/01/19/release-notes/': 'https://docs.cloud.gov/release-notes/2023/01/19/release-notes',
  '/2023/02/02/release-notes/': 'https://docs.cloud.gov/release-notes/2023/02/02/release-notes',
  '/2023/03/16/release-notes/': 'https://docs.cloud.gov/release-notes/2023/03/16/release-notes',
  '/2023/05/01/release-notes/': 'https://docs.cloud.gov/release-notes/2023/05/01/release-notes',
  '/2023/11/09/release-notes/': 'https://docs.cloud.gov/release-notes/2023/11/09/release-notes',
  '/2023/11/27/release-notes/': 'https://docs.cloud.gov/release-notes/2023/11/27/release-notes',
  '/2023/12/12/release-notes/': 'https://docs.cloud.gov/release-notes/2023/12/12/release-notes',
  '/2023/12/29/release-notes/': 'https://docs.cloud.gov/release-notes/2023/12/29/release-notes',
  '/2024/01/25/release-notes/': 'https://docs.cloud.gov/release-notes/2024/01/25/release-notes',
  '/2024/02/08/release-notes/': 'https://docs.cloud.gov/release-notes/2024/02/08/release-notes',
  '/2024/02/23/release-notes/': 'https://docs.cloud.gov/release-notes/2024/02/23/release-notes',
  '/2024/03/07/release-notes/': 'https://docs.cloud.gov/release-notes/2024/03/07/release-notes',
  '/2024/03/21/release-notes/': 'https://docs.cloud.gov/release-notes/2024/03/21/release-notes',
  '/2024/04/04/release-notes/': 'https://docs.cloud.gov/release-notes/2024/04/04/release-notes',
  '/2024/04/18/release-notes/': 'https://docs.cloud.gov/release-notes/2024/04/18/release-notes',
  '/2024/05/16/release-notes/': 'https://docs.cloud.gov/release-notes/2024/05/16/release-notes',
  '/2024/05/30/release-notes/': 'https://docs.cloud.gov/release-notes/2024/05/30/release-notes',
  '/2024/08/08/release-notes/': 'https://docs.cloud.gov/release-notes/2024/08/08/release-notes',
  '/2024/11/14/release-notes/': 'https://docs.cloud.gov/release-notes/2024/11/14/release-notes',
  '/2024/11/18/release-notes/': 'https://docs.cloud.gov/release-notes/2024/11/18/release-notes',

  '/knowledge-base/': 'https://docs.cloud.gov/blog',
  '/knowledge-base/2021-05-17-troubleshooting-ssh-connections/': 'https://docs.cloud.gov/blog/2021/05/17/troubleshooting-ssh-connections',
  '/knowledge-base/2021-05-20-connecting-to-brokered-service-instances/': 'https://docs.cloud.gov/blog/2021/05/20/connecting-to-brokered-service-instances',
  '/knowledge-base/2021-05-20-getting-rds-version-information/': 'https://docs.cloud.gov/blog/2021/05/20/getting-rds-version-information',
  '/knowledge-base/2021-05-20-managing-buildpack-changes/': 'https://docs.cloud.gov/blog/2021/05/20/managing-buildpack-changes',
  '/knowledge-base/2021-05-24-secureauth-issues/': 'https://docs.cloud.gov/blog/2021/05/24/secureauth-issues',
  '/knowledge-base/2021-07-26-app-restarts/': 'https://docs.cloud.gov/blog/2021/07/26/app-restarts',
  '/knowledge-base/2021-09-15-creating-external-domain-service/': 'https://docs.cloud.gov/blog/2021/09/15/creating-external-domain-service',
  '/knowledge-base/2021-09-21-sending-emails-from-clouddotgov/': 'https://docs.cloud.gov/blog/2021/09/21/sending-emails-from-clouddotgov',
  '/knowledge-base/2021-10-05-restricting-access-to-apps/': 'https://docs.cloud.gov/blog/2021/10/05/restricting-access-to-apps',
  '/knowledge-base/2021-12-16-managing-egress-traffic/': 'https://docs.cloud.gov/blog/2021/12/16/managing-egress-traffic',
  '/knowledge-base/2022-05-05-creating-postgresql-databases-from-shared-rds/': 'https://docs.cloud.gov/blog/2022/05/05/creating-postgresql-databases-from-shared-rds',
  '/knowledge-base/2022-08-08-adding-users-to-sandbox/': 'https://docs.cloud.gov/blog/2022/08/08/adding-users-to-sandbox',
  '/knowledge-base/2022-11-04-Encryption-In-Transit/': 'https://docs.cloud.gov/blog/2022/11/04/Encryption-In-Transit',
  '/knowledge-base/2022-11-04-fixing-certificate-errors-aws-egress-proxy/': 'https://docs.cloud.gov/blog/2022/11/04/fixing-certificate-errors-aws-egress-proxy',
  '/knowledge-base/2023-02-13-Connecting-PostgreSQL-RDS-instance-to-S3/': 'https://docs.cloud.gov/blog/2023/02/13/Connecting-PostgreSQL-RDS-instance-to-S3',
  '/knowledge-base/2023-03-28-CloudFoundry-Key-Error/': 'https://docs.cloud.gov/blog/2023/03/28/CloudFoundry-Key-Error',
  '/knowledge-base/2023-04-18-Sidecar-Processes/': 'https://docs.cloud.gov/blog/2023/04/18/Sidecar-Processes',
  '/knowledge-base/2023-08-07-advantages-of-multiple-application-instances/': 'https://docs.cloud.gov/blog/2023/08/07/advantages-of-multiple-application-instances',
  '/knowledge-base/2024-01-24-how-cloud.gov-continually-adapts-to-dynamic-cybersecurity-threats/': 'https://docs.cloud.gov/blog/2024/01/24/how-cloud.gov-continually-adapts-to-dynamic-cybersecurity-threats',
  '/knowledge-base/2024-03-25-monitoring-app-metrics/': 'https://docs.cloud.gov/blog/2024/03/25/monitoring-app-metrics',
  '/knowledge-base/2024-12-02-php-buildpack-failed-to-clone-git-repository-issue/': 'https://docs.cloud.gov/blog/2024/12/02/php-buildpack-failed-to-clone-git-repository-issue',
  '/knowledge-base/2024-12-06-migrating-opensearch/': 'https://docs.cloud.gov/blog/2024/12/06/migrating-opensearch',
  '/knowledge-base/2024-12-09-apt-buildpack-cache-issue/': 'https://docs.cloud.gov/blog/2024/12/09/apt-buildpack-cache-issue',
  '/knowledge-base/2024-12-10-using-opensearch-dashboards/': 'https://docs.cloud.gov/blog/2024/12/10/using-opensearch-dashboards',
  '/knowledge-base/2025-03-27-monitoring-app-metrics-opensearch/': 'https://docs.cloud.gov/blog/2025/03/27/monitoring-app-metrics-opensearch',

  '/pages/knowledge-base/': 'https://docs.cloud.gov/blog',
  '/pages/knowledge-base/dependabot-with-pages/': 'https://docs.cloud.gov/blog/2023/05/22/dependabot-with-pages',
  '/pages/knowledge-base/repository-best-practices/': 'https://docs.cloud.gov/blog/2024/04/23/repository-best-practices',
  '/pages/knowledge-base/single-page-application/': 'https://docs.cloud.gov/blog/2023/11/09/single-page-application',
  '/pages/knowledge-base/website-api/': 'https://docs.cloud.gov/blog/2024/03/06/website-api',

// these are all wrong or missing
  '/2015/05/29/week-update': '/404',
  '/2015/09/01/sprint-4-update': '/404',
  '/2015/09/14/sprint-5-update': '/404',
  '/2016/02/12/logs-update/': '/404',
  '/2016/06/15/auth-ssh-changes': '/404',
  '/2016/07/07/deck-update': '/404',
  '/2016/07/19/fedramp-ready': '/404',
  '/2016/12/21/ew-sandbox-deprecation': '/404',
  '/2017/02/02/fedramp-authorized': '/404',
  '/2017/05/24/get-what-you-need': '/404',
  '/2017/07/07/changes-to-credentials-broker': '/404',
  '/2017/08/11/continuous-improvement-more-tools-help-use-cloud-gov': '/404',
  '/2017/08/22/max-gov-migration-instructions': '/404',
  '/2017/08/31/release-notes-plus-join-september-workshop': '/404',
  '/2017/09/12/high-availability-redis-upcoming-workshop-more-from-cloud-gov': '/404',
  '/2017/11/20/release-notes-buildpacks-volume-services-other-new-features': '/404',
  '/2017/12/08/starting-now-sandboxes-expire-after-90-days': '/404',
  '/2017/12/27/new-homepage-quickstart-guide-more': '/404',
  '/2018/01/05/meltdown-statement': '/404',
  '/2018/01/11/outage-postmortem/': '/404',
  '/2018/02/13/elasticsearch-56-upcoming-cloud-foundry-summit-and-platform-updates/': '/404',
  '/2018/03/14/TLS-10-and-11-support-deprecated-Drupal-8-made-easy-and-platform-updates/': '/404',
  '/2018/05/21/new-custom-domain-service': '/404',
  '/2018/10/22/s3-sandbox-plan': '/404',
  '/2019/02/26/quarterly-update': '/404',
  '/2019/05/13/cflinuxfs2-final-warning/': '/404',
  '/2019/07/12/VPN-backhaul-drupal-8-and-new-team-members/': '/404',
  '/2019/08/26/changes-to-cloud-gov-services-and-prices': '/404',
  '/2019/09/16/deprecation-policy': '/404',
  '/2019/09/25/v12-is-here': '/404',
  '/2020/02/27/new-dashboard': '/404',
  '/2020/04/22/introducing-the-cloud-gov-tech-talk-series': '/404',
  '/2020/04/28/changes-to-cloud-govs-existing-cdn-and-custom-domain-services': '/404',
  '/2020/05/12/try-a-free-sandbox-space': '/404',
  '/2020/08/27/running-dot-net-apps-on-cloud-dot-gov': '/404',
  '/2020/11/10/elasticsearch_and_redis_deprecation_notice': '/404',
  '/2020/12/18/cloud-gov_not_impacted_by_solarwinds_orion_code_compromise_-_cisa_directive_21-01/': '/404',
  '/2020/12/29/getting_to_know_new_features_with_the_cf7_cli_rolling_app_deployments/': '/404',
  '/2021/01/29/disabling_inactive_cloud_gov_idp_accounts/': '/404',
  '/2021/02/05/cloud-gov_a_different_kind_of_cloud/': '/404',
  '/2021/02/17/writing_a_cloud-gov_ssp_system_environment/': '/404',
  '/2021/03/05/cloud-gov_tech_talk_-_internal_routes': '/404',
  '/2021/04/02/shared-db-deprecation-notice': '/404',
  '/2021/05/10/how_cloud-gov_prioritizes_organizes_work/': '/404',
  '/2021/05/26/changes_to_the_nodejs_buildpack': '/404',
  '/2021/06/08/changes-to-buildpacks': '/404',
  '/2021/07/02/migrating-from-legacy-drupal-to-federalist': '/404',
  '/2021/08/03/update_to_our_customer_responsibility_matrix_crm': '/404',
  '/2021/08/16/external-domain-migration-announcement': '/404',
  '/2021/10/04/invalid-certificate-error': '/404',
  '/2021/11/15/dhs-bod-22-01/': '/404',
  '/2021/11/16/controlled-space-egress': '/404',
  '/2021/11/30/cloud-gov_more_than_a_stepping_stone_to_the_cloud/': '/404',
  '/2021/12/14/log4j-buildpack-updates': '/404',
  '/2021/12/22/log4j_vulnerability_bod_22-02_update/': '/404',
  '/2022/02/09/sharing-service-instances': '/404',
  '/2022/04/06/encrypted-container-to-container-networking': '/404',
  '/2022/04/25/deprecation-notice': '/404',
  '/2022/06/29/cloud-dot-gov-scalability-and-resiliance/': '/404',
  '/2022/11/15/pages-crm-release': '/404',
  '/2023/02/02/cloud-gov-pages-site-auth-changes': '/404',
  '/2023/02/02/cloud-gov-pages-unmigrated-user-policy': '/404',
  '/2023/02/23/cloud-gov-pages-faster-builds': '/404',
  '/2023/03/08/cloud-gov-pages-cve-2022-28923': '/404',
  '/2023/03/28/cflinuxfs3-deprecation': '/404',
  '/2023/04/19/opensearch-maintenance': '/404',
  '/2023/04/27/cflinuxfs3-deprecation-update': '/404',
  '/2023/05/16/cflinuxfs3-buildpack-deprecation': '/404',
  '/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade': '/404',
  '/2023/06/01/compliance-office-hours': '/404',
  '/2023/06/05/aws-ending-support-mysql-57': '/404',
  '/2023/07/03/independence-day-office-hours': '/404',
  '/2023/08/01/2023-8-1-postgresql-versions-update': '/404',
  '/2023/08/01/fedramp-csp-community/': '/404',
  '/2023/09/18/storage-volumes-gp3': '/404',
  '/2023/09/25/federalist-ato': '/404',
  '/2023/10/11/update-existing-instances-gp3-now-available': '/404',
  '/2023/11/09/platform-protections': '/404',
  '/2024/11/21/new-logging-system': '/404',
  '/2025/01/07/pages-build-default-node20': '/404',
  '/2025/01/07/v2api-deprecation': '/404',
  '/2025/05/06/new-external-domain-managed-policies': '/404',
  '/2025/05/08/audit-events-opensearch': '/404',
  '/2025/06/10/metrics-opensearch': '/404',
  '/2025/06/17/v2api-eol-delay': '/404',
  '/2025/07/03/rds-read-replicas-available/': '/404',

  '/docs/ops/moved/':'https://docs.cloud.gov/platform/compliance/incident-response-planning'

  // possible formats
  // '/old': '/new',
  // '/blog/[...slug]': '/articles/[...slug]', // only if using getStaticPaths()
  // '/about': 'https://example.com/about',
  // '/news': {
  //   status: 302, // Specify exact status code
  //   destination: 'https://example.com/news'
  // },
}
export default redirects;