title: cloud.gov
email: support@cloud.gov
support_email_address: support@cloud.gov
description: >- # this means to ignore newlines until "baseurl:"
  Expedite your agency’s path to a secure and compliant cloud. cloud.gov provides an application environment that enables rapid deployment and ATO assessment for modern web applications.
baseurl: "" # the subpath of your site, e.g. /knowledge-base
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Twitter handle. Only the handle, not the URL.
# twitter: clouddotgov
github_url: https://github.com/cloud-gov/cg-site
support_email: mailto:support@cloud.gov?body=What+is+your+question%3F%0D%0A%0D%0APlease+provide+your+application+name+or+URL.+Do+not+include+any+sensitive+information+about+your+platform+in+this+email.
inquiries_email: mailto:inquiries@cloud.gov?body=What%27s%20your%20name%3F%0A%0AWhat%20agency%20or%20office%20do%20you%20work%20for%3F%0A%0AWhat%27s%20your%20job%20title%20or%20role%3F%0A%0ATell%20us%20a%20little%20about%20your%20project%20or%20your%20questions%20about%20cloud.gov%3A%0A%0AIf%20you%27d%20like%20us%20to%20call%20you%2C%20what%27s%20your%20phone%20number%20and%20when%20might%20be%20a%20good%20time%3F%0A%0AHow%20did%20you%20first%20hear%20about%20cloud.gov%3F

github_branch: main

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-34

# Configuration for DAP, add your agency ID here:
dap_agency: GSA
dap_subagency: TTS,cloud.gov

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
# agency: your-agency

# Optional
# subagency: your-subagency

# Configuration for Google Analytics
ga:
# ua: your-ua

# Site Navigation
primary_navigation:
  - name: Why cloud.gov?
    key: overview
    children:
      - name: Overview
        url: /docs/overview/what-is-cloudgov/
      - name: We’re FedRAMP authorized
        url: /docs/overview/fedramp-tracker/
      - name: Applications we support
        url: /docs/overview/portfolio-analysis/
      - name: Benefits of PaaS
        url: /docs/technology/responsibilities/
      - name: Customer stories
        url: /docs/customer-stories/epa-airnow-gov/
      - name: Our team
        url: /docs/overview/cloudgov-team/
  - name: Get started
    url: /sign-up/
  - name: Pricing
    key: pricing
    children:
      - name: Pricing
        url: /pricing/
      - name: Try a Free Sandbox
        url: /docs/pricing/free-limited-sandbox/
  - name: Documentation
    key: docs
    children:
      - name: Deploying apps
        url: /docs/deployment/deployment/
      - name: Managing apps
        url: /docs/management/plugins/
      - name: Managing services
        url: /docs/services/intro/
      - name: Managing orgs
        url: /docs/orgs-spaces/dashboard/
  - name: News
    url: /news/
  - name: Knowledge base
    url: /knowledge-base/
  - name: Pages
    url: /pages/
  - name: Contact us
    url: /contact/

secondary_navigation:
  - name: Platform Status
    url: https://cloudgov.statuspage.io/
  - name: Log in
    url: https://login.fr.cloud.gov/login

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  endpoint: https://search.usa.gov # You should not change this.
  affiliate: cloud.gov
  access_key: v_vjJAaWUAy1wHDmCPVM7zEvyH7-gbS1WeYhoEA_X9o=
  inline: false #this renders the results on the same domain. Otherwise, it will render the results in the search.gov domain
  suggestions: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

permalink: pretty

url: "https://cloud.gov"


### plugin settings ###
last-modified-at:
  date-format: "%Y-%m-%d"

