title: cloud.gov
email: support@cloud.gov
support_email_address: support@cloud.gov
description: >- # this means to ignore newlines until "baseurl:"
  Expedite your agency’s path to a secure and compliant cloud. cloud.gov provides an application environment that enables rapid deployment and ATO assessment for modern web applications.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Twitter handle. Only the handle, not the URL.
twitter: clouddotgov
github_url: https://github.com/cloud-gov/cg-site
support_email: mailto:support@cloud.gov?body=What+is+your+question%3F%0D%0A%0D%0APlease+provide+your+application+name+or+URL.+Do+not+include+any+sensitive+information+about+your+platform+in+this+email.
inquiries_email: mailto:inquiries@cloud.gov?body=What%27s%20your%20name%3F%0A%0AWhat%20agency%20or%20office%20do%20you%20work%20for%3F%0A%0AWhat%27s%20your%20job%20title%20or%20role%3F%0A%0ATell%20us%20a%20little%20about%20your%20project%20or%20your%20questions%20about%20cloud.gov%3A%0A%0AIf%20you%27d%20like%20us%20to%20call%20you%2C%20what%27s%20your%20phone%20number%20and%20when%20might%20be%20a%20good%20time%3F%0A%0AHow%20did%20you%20first%20hear%20about%20cloud.gov%3F

github_branch: main

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-34

# Configuration for DAP, add your agency ID here:
dap_agency: GSA
dap_subagency: TTS,cloud.gov

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Why cloud.gov?
    key: overview
    children:
      - name: Overview
        url: /docs/overview/what-is-cloudgov/
      - name: We’re FedRAMP authorized
        url: /docs/overview/fedramp-tracker/
      - name: Applications we support
        url: /docs/overview/portfolio-analysis/
      - name: Benefits of PaaS
        url: /docs/technology/responsibilities/
      - name: Customer stories
        url: /docs/customer-stories/epa-airnow-gov/
      - name: Our team
        url: /docs/overview/cloudgov-team/
  - name: Get started
    url: /sign-up/
  - name: Pricing
    key: pricing
    children:
      - name: Pricing
        url: /pricing/
      - name: Try a Free Sandbox
        url: /docs/pricing/free-limited-sandbox/
      - name: Quota Costs Billing & Limits
        url: /docs/pricing/quotas/
      - name: Support Packages
        url: /support-packages/
  - name: Documentation
    key: docs
    children:
      - name: Deploying apps
        url: /docs/deployment/deployment/
      - name: Managing apps
        url: /docs/management/plugins/
      - name: Managing services
        url: /docs/services/intro/
      - name: Managing orgs
        url: /docs/orgs-spaces/dashboard/
  - name: News
    url: /news/
  - name: Knowledge base
    url: /knowledge-base/
  - name: Pages
    url: /pages/
  - name: Contact us
    url: /contact/

secondary_navigation:
  - name: Platform Status
    url: https://cloudgov.statuspage.io/
  - name: Log in
    url: https://login.fr.cloud.gov/login

documentation_navigation:
  - name: "Overview"
    identifier: "overview"
    icon: fa-home
    weight: -150
  - name: "Technology and security"
    identifier: "technology"
    icon: fa-lock
    weight: -130
  - name: "Customer stories"
    identifier: "customer-stories"
    icon: fa-star
    weight: -120
  - name: "Getting started"
    identifier: "getting-started"
    icon: fa-road
    weight: -115
  - name: "Deploying apps"
    identifier: "deployment"
    icon: fa-file-text
    weight: -110
  - name: "Services"
    identifier: "services"
    icon: fa-database
    weight: -100
  - name: "Managing apps"
    identifier: "management"
    icon: fa-rocket
    weight: -100
  - name: "Managing orgs"
    identifier: "orgs-spaces"
    icon: fa-users
    weight: -100
  - name: "Compliance"
    identifier: "compliance"
    icon: fa-check-square-o
    weight: -95
  - name: "Team documentation"
    identifier: "ops"
    icon: fa-wrench

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  endpoint: https://search.usa.gov # You should not change this.
  affiliate: cloud.gov
  access_key: v_vjJAaWUAy1wHDmCPVM7zEvyH7-gbS1WeYhoEA_X9o=
  inline: false #this renders the results on the same domain. Otherwise, it will render the results in the search.gov domain
  suggestions: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################


collections:
  pages:
    output: true
    permalink: /:path/
  docs:
    output: true
    permalink: /:collection/:path/
  kbarticles:
    output: true
    permalink: /knowledge-base/:path/
  kbarticlespages:
    output: true
    permalink: /pages/knowledge-base/:path/

permalink: pretty

markdown: kramdown
url: "https://cloud.gov"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .parcel-cache

### plugin settings ###
last-modified-at:
  date-format: "%Y-%m-%d"


defaults:
  - scope:
      path: "docs/compliance"
    values:
      toc: true
  - scope:
      path: "docs/deployment"
    values:
      toc: true
  - scope:
      path: "docs/getting-started"
    values:
      toc: true
  - scope:
      path: "docs/management"
    values:
      toc: true
  - scope:
      path: "docs/orgs-spaces"
    values:
      toc: true
  - scope:
      path: "docs/overview"
    values:
      toc: true
  - scope:
      path: "docs/pricing"
    values:
      toc: true
  - scope:
      path: "docs/services"
    values:
      toc: true
  - scope:
      path: "docs/technology"
    values:
      toc: true


toc:
  min_level: 2
  max_level: 2
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-



sidenav:
  - text: Using Pages
    href: /pages/documentation/
    subfolderitems:
      - text: Why use Pages?
        href: /pages/documentation/why-use-pages/
      - text: Access and permissions
        href: /pages/documentation/access-permissions/
      - text: Adding a user to an Organization
        href: /pages/documentation/adding-users/
      - text: Before you launch
        href: /pages/documentation/before-you-launch/
      - text: Getting started with a sandbox
        href: /pages/documentation/sandbox/
      - text: "21st Century IDEA"
        href: /pages/documentation/21st-century-idea/
      - text: Getting started with Decap CMS
        href: /pages/documentation/getting-started-with-decap-cms/
      - text: Included with Pages
        href: /pages/documentation/included-with-pages/
      - text: Instructional demos
        href: /pages/documentation/instructional-demos/
      - text: Builds and previews
        href: /pages/documentation/previews/
      - text: Custom domains
        href: /pages/documentation/custom-domains/
      - text: Migration guide
        href: /pages/documentation/migration-guide/
      - text: Adding forms
        href: /pages/documentation/forms/
      - text: Adding search
        href: /pages/documentation/search/
      - text: Site templates
        href: /pages/documentation/templates/
      - text: Customizing your site
        href: /pages/documentation/customization/
      - text: Using the markup languages
        href: /pages/documentation/resources/
      - text: Content guide
        href: /pages/documentation/content-guide/
      - text: Custom headers
        href: /pages/documentation/custom-headers/
      - text: Federalist.json
        href: /pages/documentation/federalist-json/
  - text: For security and compliance
    href: /pages/documentation/
    subfolderitems:
      - text: Security and Compliance
        href: /pages/documentation/security-and-compliance
      - text: Customer responsibilities
        href: /pages/documentation/customer-responsibilities/
      - text: FedRAMP Tracker
        href: /docs/overview/fedramp-tracker/
      - text: Automated Site Reports
        href: /pages/documentation/automated-site-reports/
  - text: For developers
    href: /pages/documentation/
    subfolderitems:
      - text: How builds work
        href: /pages/documentation/how-builds-work/
      - text: Specific build errors
        href: /pages/documentation/build-errors/
      - text: Environment variables on builds
        href: /pages/documentation/env-vars-on-pages-builds/
      - text: Pages and cloud.gov
        href: /pages/documentation/cloud-gov/
      - text: Node on Pages
        href: /pages/documentation/node-on-pages/
      - text: RVM on Pages
        href: /pages/documentation/rvm-on-pages/
      - text: Bundler on Pages
        href: /pages/documentation/bundler-on-pages/
      - text: Caching Build Dependencies
        href: /pages/documentation/cache-dependencies/
      - text: Supported site engines
        href: /pages/documentation/supported-site-engines/
      - text: Large file handling
        href: /pages/documentation/large-file-handling/
      - text: Renaming your site's repository
        href: /pages/documentation/renaming-site-repository/
      - text: Monorepos on Pages
        href: /pages/documentation/monorepos-on-pages/
      - text: External tools and resources
        href: /pages/documentation/external-tools-and-resources/
